#!/bin/sh
[ "$ACTION" = ifup ] || exit 0
ifname=WANCMCCv6
device=eth0.3
[ -z "$ifname" -o "$INTERFACE" = "$ifname" ] || exit 0
ip -6 route add `ip -6 route show default| grep $device | grep via | sed -e 's/from [^ ]* //' | sed -e '2,$d'`
logger -t IPv6 "Add IPv6 default route for WANCMCC."

